version: 0.2

# env:
#   shell: shell-tag
#   variables:
#     key: "value"
#     key: "value"
#   parameter-store:
#     key: "value"
#     key: "value"
#   exported-variables:
#     - variable
#     - variable
#   secrets-manager:
#     key: secret-id:json-key:version-stage:version-id
#   git-credential-helper: no | yes

        
phases:
  build:
    commands:
      - go test
      - docker build -t git.systementor.se/hannes.westin/cloudnativeassignment .
      - docker login -u hannes.westin -p yacloud1 https://git.systementor.se
      - docker push git.systementor.se/hannes.westin/cloudnativeassignment 